// Every blog post lives in its own folder under app/blog/<slug>.
// Reading that folder at runtime does not work on Vercel — the app/ sources
// are not part of the serverless bundle — so the slugs are listed here.
// Add a new post's slug when you add its folder.
export const BLOG_SLUGS: string[] = [
  '11-11-portaal-2025-hoger-bewustzijn',
  'agaat-betekenis-soorten-kleuren-werking',
  'amethist-soorten-werking-spirituele-tips',
  'art-of-stones-s4h-edelstenen',
  'bergkristal-koning-kristallen',
  'chakra-kristallen-complete-gids',
  'chakras-en-hun-kleuren',
  'chakras-uitgelegd-energiesysteem',
  'citrien-amethist-zon-maan-edelstenen',
  'dromen-technologie-simulatie-leven',
  'edelstenen-betekenis-kracht-malachiet-lavasteen-onyx-howliet-sodaliet-unakiet',
  'edelstenen-chinees-sterrenbeeld-gelukssteen',
  'edelstenen-geld-rijkdom-overvloed',
  'edelstenen-liefde-zelfliefde-hartchakra',
  'edelstenen-opladen-maanlicht',
  'edelstenen-per-levenspad-spirituele-gidssteen',
  'edelstenen-per-sterrenbeeld-numerologie',
  'gouden-driehoek-amethist-bergkristal-rozenkwarts',
  'jaar-van-de-houten-slang-2025',
  'jaar-van-het-vuurpaard-2026',
  'koshi-windgongs-magische-klanken-rust-yoga-sound',
  'lapis-lazuli-hemelsteen-egypte-innerlijke-wijsheid',
  'masters-of-shilajit-himalaya',
  'morganiet-rhodoniet-liefde-heling',
  'numerologie-astrologie-taal-universum',
  'quantumrealiteit-bewustzijn-energie',
  'rozenkwarts-steen-van-de-liefde',
  's4h-koperen-armbanden-magneten',
  's4h-ruwe-rozenkwarts-pure-liefde',
  's4h-sieraden-spirituele-kracht-stijl',
  'supermaan-oktober-2025',
  'top-10-bekendste-onbekendste-edelstenen',
  'top-7-edelstenen-donkere-maanden',
  'volle-maan-december-2025',
  'volle-maan-november-2025',
  'volle-maan-oktober-2025',
  'zaphir-shanti-chimes-kwaliteit-authenticiteit-harmonie',
  'zilveren-koord-slapen-zoutlampen-spirituele-tips',
];
